services:
  sylius.shop.block_event_listener.javascripts:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@AlmaSyliusPaymentPlugin/_partials/_javascript.html.twig'
    tags:
      -
        name: kernel.event_listener,
        event: sylius.shop.layout.javascripts,
        method: onBlockEvent
