services:
  _defaults:
    public: true
    autowire: true

  alma_sylius_payment_plugin.controller.installments:
    class: Alma\SyliusPaymentPlugin\Controller\InstallmentsController
    public: true
    tags: [ 'controller.service_arguments' ]
