services:
  _defaults:
    public: true
    autowire: true

  Alma\SyliusPaymentPlugin\Controller\InstallmentsController:
    class: Alma\SyliusPaymentPlugin\Controller\InstallmentsController
    public: true
    arguments:
      $twig: '@twig'
      $orderRepository: '@sylius.repository.order'
      $paymentMethodRepository: '@sylius.repository.payment_method'
      $almaBridge: '@alma_sylius_payment_plugin.bridge'
      $localeContext: '@sylius.context.locale'
      $localeProcessor: '@Sylius\PayPalPlugin\Processor\LocaleProcessorInterface'
    tags: [ 'controller.service_arguments' ]
