services:
  _defaults:
    public: true
    autowire: true

  Alma\SyliusPaymentPlugin\Controller\InstallmentsController:
    class: Alma\SyliusPaymentPlugin\Controller\InstallmentsController
    public: true
    arguments:
      $twig: '@twig'
    tags: [ 'controller.service_arguments' ]
